### ISSUE TITLE
json formatting for bind has trailing commas

### ISSUE THREAD

**Issue by rothgar** [agonzalezro/escheduler#1]
The binding json has trailing commas after pod_name and node_name

https://github.com/agonzalezro/escheduler/blob/master/lib/escheduler.ex#L35-L40

Maybe elixer does formatting/linting that I'm not aware of but using that json with curl gives a formatting error. Also checking it on jsonlint.com shows it's not valid.

I didn't actually try running it but I was just curious if it works the way it is or if you know when/how the extra commas get stripped.

Thanks for the example

**Comment by agonzalezro** [comment]
Hi @rothgar,

it's not JSON, it's a map. Perhaps avoiding the `"` it would be clear:

```
iex(1)> rothgar = %{
...(1)>   "a": 1,
...(1)>   "b": 2,
...(1)> }
%{a: 1, b: 2}
iex(2)> Map.get(rothgar, :b)
2
iex(3)> alex = %{
...(3)>   "c": 3,
...(3)>   "d": 4
...(3)> }
%{c: 3, d: 4}
iex(4)> Map.get(alex, :d)
4
```

Thanks for the comment, feel free to close the issue if it's clear.

**Comment by rothgar** [comment]
ahh, thanks so much for the clarification. I'm not familiar with the language so I shouldn't have made the assumption.
